import type { Metadata } from "next";
import { Kaisei_Opti, Josefin_Slab } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const kaisseiOpti = Kaisei_Opti({ weight: ["400"], subsets: ["latin"] });
const josefinSlab = Josefin_Slab({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-josefinSlab",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${kaisseiOpti.className} ${josefinSlab.variable} bg-black text-white `}
      >
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
